name: PomCare
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  image_picker: ^1.1.2
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.32.12
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.5
  fl_chart: ^0.68.0
  http_parser: ^4.1.2
  geolocator: ^13.0.2
  sqflite: ^2.4.1
  path: ^1.9.0
  crypto: ^3.0.6
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.0
  cloud_firestore: ^6.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/farm_bg.jpeg
    - assets/images/farm_bg1.jpeg
    - assets/images/farm_bg2.jpeg
    - assets/images/farm_bg3.jpeg
    - assets/images/farm_bg4.jpeg
    - assets/models/pomegranat_quality_model.tflite
    - assets/models/labels.txt
    - assets/models/pomegranate_irrigation_model.tflite
    - assets/models/irrigation_labels.txt
    - assets/models/fertilizert.tflite
    - assets/models/fertilizer_labels.txt
    - assets/images/pomegranate.jpeg
    - assets/images/bud.png
    - assets/images/early_fruit.png
    - assets/images/mid_growth.png
    - assets/images/Mature.png
    - assets/images/Flower.jpg
    - assets/images/Early_Fruit.jpg
    - assets/images/Mature_fruit.jpg
    - assets/images/Mid_Growth.jpg
    - assets/models/pomegranate_yolo.tflite
    - assets/models/pomegranate_cnn.tflite
    - assets/models/growth_yolo_labels.txt
    - assets/models/growth_cnn_labels.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon1.png"
  assets:
    - assets/images/pomegranate.jpeg
    - assets/images/bud.png
    - assets/images/early_fruit.png
    - assets/images/mid_growth.png
    - assets/images/Mature.png
    - assets/images/Flower.jpg
    - assets/images/Early_Fruit.jpg
    - assets/images/Mature_fruit.jpg
    - assets/images/Mid_Growth.jpg
