// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHsuWBJvfzbJaV2D6G7haPeuVBwgZWoQ',
    appId: '1:95668202756:web:e9df55298746715af5f451',
    messagingSenderId: '95668202756',
    projectId: 'r26-it-087',
    authDomain: 'r26-it-087.firebaseapp.com',
    storageBucket: 'r26-it-087.firebasestorage.app',
    measurementId: 'G-RX64KGLSY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFom2LMyYA-gdmGulLoxtmNA7hsQtEaKk',
    appId: '1:95668202756:android:c266a7c2ad4cf010f5f451',
    messagingSenderId: '95668202756',
    projectId: 'r26-it-087',
    storageBucket: 'r26-it-087.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBroyJwuSWQw9ZFM6pzHfZxYS47wma440I',
    appId: '1:95668202756:ios:0eac9d747ab456abf5f451',
    messagingSenderId: '95668202756',
    projectId: 'r26-it-087',
    storageBucket: 'r26-it-087.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBroyJwuSWQw9ZFM6pzHfZxYS47wma440I',
    appId: '1:95668202756:ios:0eac9d747ab456abf5f451',
    messagingSenderId: '95668202756',
    projectId: 'r26-it-087',
    storageBucket: 'r26-it-087.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMHsuWBJvfzbJaV2D6G7haPeuVBwgZWoQ',
    appId: '1:95668202756:web:a331929ad9e7ac63f5f451',
    messagingSenderId: '95668202756',
    projectId: 'r26-it-087',
    authDomain: 'r26-it-087.firebaseapp.com',
    storageBucket: 'r26-it-087.firebasestorage.app',
    measurementId: 'G-4Y4EJ8120P',
  );
}
